### ISSUE TITLE
Testing from a non-collaborator

### ISSUE THREAD

**Issue by githubteacher** [brntbeer/teach.github.com#6]
@brntbeer I think we need an issue to talk about your latest commits.

/cc @broccolini sorry for the mention. Just throwing you under a bus. :bus:

**Comment by brntbeer** [comment]
Thank you! Taking the lead on this one. Which commit did you mean?

**Comment by githubteacher** [comment]
talking about ca6273c

**Comment by githubteacher** [comment]
Also, this bit needs worked on: https://github.com/brntbeer/teach.github.com/blob/collaboration-testing/stylesheets/page.css#L1-12
